version: '3.8'

services:
  api:
    build: .
    container_name: meta_ads_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    # Esto asegura que los cambios en el c√≥digo se reflejen si montas el volumen
    volumes:
      - .:/app
    networks:
      - ads_network

networks:
  ads_network:
    driver: bridge
