version: '3.8'

services:
  # SERVICIO DE BACKEND (manejoapi.libresdeumas.com)
  backend:
    build: .
    container_name: meta_backend_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - ads_network

  # SERVICIO DE FRONTEND (manejometa.libresdeumas.com)
  # Usamos un servidor ligero de archivos est√°ticos
  frontend:
    image: nginx:alpine
    container_name: meta_frontend_ui
    ports:
      - "81:81"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      # - ./App.jsx:/usr/share/nginx/html/App.jsx # Si se carga externamente
    restart: always
    networks:
      - ads_network

networks:
  ads_network:
    driver: bridge
