services:
  # BACKEND: manejoapi.libresdeumas.com (Puerto 8000)
  backend:
    build: .
    container_name: meta_backend_api
    ports:
      - "80:8000"
    env_file:
      - .env
    restart: always

  # FRONTEND: manejometa.libresdeumas.com (Puerto 3000)
  frontend:
    image: nginx:alpine
    container_name: meta_frontend_ui
    ports:
      - "8000:80" # Frontend accesible en el puerto 3000 del host
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./App.jsx:/usr/share/nginx/html/App.jsx
    restart: always
